#                                              Pandas Assignment 1A



### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

### Step 2. Import the dataset

In [ ]:
df = pd.read_csv('Pandas Assign 1(A).tsv' , sep='\t')

### Step 3. Assign it to a variable called chipo.

In [ ]:
chipo = pd.read_csv('Pandas Assign 1(A).tsv' , sep='\t')

### Step 4. See the first 10 entries

In [ ]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [ ]:
chipo.info

<bound method DataFrame.info of       order_id  quantity                              item_name  \
0            1         1           Chips and Fresh Tomato Salsa
1            1         1                                   Izze
2            1         1                       Nantucket Nectar
3            1         1  Chips and Tomatillo-Green Chili Salsa
4            2         2                           Chicken Bowl
...        ...       ...                                    ...
4617      1833         1                          Steak Burrito
4618      1833         1                          Steak Burrito
4619      1834         1                     Chicken Salad Bowl
4620      1834         1                     Chicken Salad Bowl
4621      1834         1                     Chicken Salad Bowl

                                     choice_description item_price
0                                                   NaN     $2.39
1                                          [Clementine]     $3.39
2                                               [Apple]     $3.39
3                                                   NaN     $2.39
4     [Tomatillo-Red Chili Salsa (Hot), [Black Beans...    $16.98
...                                                 ...        ...
4617  [Fresh Tomato Salsa, [Rice, Black Beans, Sour ...    $11.75
4618  [Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...    $11.75
4619  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...    $11.25
4620  [Fresh Tomato Salsa, [Fajita Vegetables, Lettu...     $8.75
4621  [Fresh Tomato Salsa, [Fajita Vegetables, Pinto...     $8.75

[4622 rows x 5 columns]>

In [ ]:
chipo.shape

(4622, 5)

### Step 6. What is the number of columns in the dataset?

In [ ]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [ ]:
chipo.columns.values

array(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'], dtype=object)

### Step 8. How is the dataset indexed?

In [ ]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [ ]:
chipo.item_name.nunique

50

### Step 10. For the most-ordered item, how many items were ordered?

In [ ]:
chipo.item_name.value_counts()

item_name
Chicken Bowl                             726
Chicken Burrito                          553
Chips and Guacamole                      479
Steak Burrito                            368
Canned Soft Drink                        301
Steak Bowl                               211
Chips                                    211
Bottled Water                            162
Chicken Soft Tacos                       115
Chips and Fresh Tomato Salsa             110
Chicken Salad Bowl                       110
Canned Soda                              104
Side of Chips                            101
Veggie Burrito                            95
Barbacoa Burrito                          91
Veggie Bowl                               85
Carnitas Bowl                             68
Barbacoa Bowl                             66
Carnitas Burrito                          59
Steak Soft Tacos                          55
6 Pack Soft Drink                         54
Chips and Tomatillo Red Chili Salsa       48
Chicken Crispy Tacos                      47
Chips and Tomatillo Green Chili Salsa     43
Carnitas Soft Tacos                       40
Steak Crispy Tacos                        35
Chips and Tomatillo-Green Chili Salsa     31
Steak Salad Bowl                          29
Nantucket Nectar                          27
Barbacoa Soft Tacos                       25
Chips and Roasted Chili Corn Salsa        22
Izze                                      20
Chips and Tomatillo-Red Chili Salsa       20
Veggie Salad Bowl                         18
Chips and Roasted Chili-Corn Salsa        18
Barbacoa Crispy Tacos                     11
Barbacoa Salad Bowl                       10
Chicken Salad                              9
Veggie Soft Tacos                          7
Carnitas Crispy Tacos                      7
Veggie Salad                               6
Carnitas Salad Bowl                        6
Burrito                                    6
Steak Salad                                4
Crispy Tacos                               2
Salad                                      2
Bowl                                       2
Chips and Mild Fresh Tomato Salsa          1
Veggie Crispy Tacos                        1
Carnitas Salad                             1
Name: count, dtype: int64

In [ ]:
chipo.groupby(['item_name']).quantity.sum().sort_values(ascending = False).index[0]

'Chicken Bowl'

### Step 11. What was the most ordered item in the choice_description column?

In [ ]:
chipo.choice_description.value_counts()

choice_description
[Diet Coke]                                                                                                                                      134
[Coke]                                                                                                                                           123
[Sprite]                                                                                                                                          77
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Lettuce]]                                                                            42
[Fresh Tomato Salsa, [Rice, Black Beans, Cheese, Sour Cream, Guacamole, Lettuce]]                                                                 40
                                                                                                                                                ...
[Fresh Tomato Salsa (Mild), [Pinto Beans, Black Beans, Rice, Cheese, Sour Cream, Lettuce]]                                                         1
[[Fresh Tomato Salsa (Mild), Roasted Chili Corn Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Pinto Beans, Cheese, Sour Cream, Lettuce]]      1
[Fresh Tomato (Mild), [Guacamole, Rice, Black Beans]]                                                                                              1
[[Tomatillo-Green Chili Salsa (Medium), Tomatillo-Red Chili Salsa (Hot)], [Black Beans, Rice, Cheese, Lettuce]]                                    1
[Tomatillo Green Chili Salsa, [Rice, Fajita Vegetables, Black Beans, Guacamole]]                                                                   1
Name: count, Length: 1043, dtype: int64

In [ ]:
chipo.groupby(['choice_description']).quantity.sum().sort_values(ascending = False).index[0]

'[Diet Coke]'

### Step 12. How many items were orderd in total?

In [ ]:
chipo.quantity.sum()

4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [ ]:
chipo.dtypes.item_price

dtype('O')

#### Step 13.b. Create a lambda function and change the type of item price

In [ ]:
chipo.item_price = chipo.item_price.apply(lambda x: float(x[1:]))

#### Step 13.c. Check the item price type

In [ ]:
chipo.item_price.dtypes

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [ ]:
chipo['revenue'] = chipo['quantity']*chipo.item_price
total_revenue = chipo.revenue.sum()
total_revenue

39237.02

### Step 15. How many orders were made in the period?

In [ ]:
chipo.order_id.value_counts()

order_id
926     23
1483    14
205     12
759     11
1786    11
        ..
768      1
341      1
1048     1
94       1
1199     1
Name: count, Length: 1834, dtype: int64

In [ ]:
total_order = chipo.order_id.nunique()
total_order

1834

### Step 16. What is the average revenue amount per order?

In [2]:
total_revenue/total_order

NameError: name 'total_revenue' is not defined

### Step 17. How many different items are sold?

In [ ]:
chipo.item_name.nunique()

50

### Step 18. How many products cost more than $10.00?

In [ ]:
chipo[chipo.item_price > 10].item_name.nunique()

31

### Step 19. What is the price of each item?
###### print a data frame with only two columns item_name and item_price

In [ ]:
chipo[['item_name', 'item_price']]

                                  item_name  item_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl       16.98
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 20. Sort by the name of the item

In [ ]:
chipo.sort_values(by='item_name')

,order_id,quantity,item_name,choice_description,item_price,revenue
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,25.96
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 21. What was the quantity of the most expensive item ordered?

In [ ]:
chipo.sort_values(by = "item_price", ascending = False).head(1)

,order_id,quantity,item_name,choice_description,item_price,revenue
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25,663.75

### Step 22. How many times were a Veggie Salad Bowl ordered?

In [ ]:
chipo.groupby('item_name').order_id.count().loc['Veggie Salad Bowl']

18

### Step 23. How many times people orderd more than one Canned Soda?

In [ ]:
chipo[(chipo.item_name == 'Canned Soda') & (chipo.quantity > 1)].shape[0]

20